language: python
python:
    - 3.4
install:
    - pip install -r requirements.txt
    - pip install coveralls
env:
  -DB=postgress
addons:
  postgresql:"9.4"
script: nosetests --with-coverage
after_success:
    - coveralls