language: python
python:
    - 3.4
install:
    - pip install -r requirements.txt
    - pip install coveralls
env:
  - DB=postgres
addons:
  - postgresql:"9.4"
before_script:
  - psql -c 'create database test_db;' -U postgres
script: nosetests --with-coverage
after_success:
    - coveralls