
# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
              - v1-dependencies-{{ checksum "requirements.txt" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
  test:

    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
        environment:
         APP_SETTINGS: testing
         DATABASE_URL: postgresql://circleci@localhost/circlecidb
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_DB: circlecidb
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: ''

    working_directory: ~/repo

    steps:
      - checkout
      - run: mkdir reports
      - restore_cache:
          keys:
              - v1-dependencies-{{ checksum "requirements.txt" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-

      - run:
         name: confirm postgres is up
         command: |
           count=0
           while [ $count -lt 12 ] ; do
              if exec 10<>/dev/tcp/127.0.0.1/5432; then
                echo "Hey, postgres is up"
                break
              fi
              sleep 5
              count=$((count + 1))
           done
           if [ $count -eq 12 ]; then
             echo "Postgres is still down!"
             exit 1
           fi
      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            nosetests --with-coverage

      - store_artifacts:
          path: reports
          destination: reports
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build